;PROGRAM 2 OF LAB 1
;FILENAME: Lab1b.asm
;FILE FORMAT: EXE

STACK_SEG SEGMENT STACK
	DB 100 DUP(?)
STACK_SEG ENDS


DATA_SEG SEGMENT 'DATA'
	MESSAGE		DB 'ECE3210 LAB1',0DH,0AH
			DB 'ENTER A CHARACTER FROM KEYBORD: $'
	OUTMSG		DB 0DH,0AH,'THE CHARACTER YOU JUST ENTERED IS: $'
	INCHAR		DB ?
	NEWLINE		DB 0DH,0AH,'$'
DATA_SEG ENDS


CODE_SEG SEGMENT PARA 'CODE'
	ASSUME CS:CODE_SEG, DS:DATA_SEG, SS:STACK_SEG

MAIN PROC FAR
MOV	AX,DATA_SEG	;INITIALIZE THE PROGRAM
MOV	DS,AX
MOV 	AX,STACK_SEG
MOV 	SS,AX
LEA	DX,MESSAGE	;PRINT MESSAGE
MOV	AH,9
INT	21H
MOV	AH,1	;READ A CHARACTER FROM KEYBOARD
INT	21H
MOV	INCHAR,AL
LEA	DX,OUTMSG	;PRINT A MESSAGE
MOV	AH,9
INT	21H
MOV	DL,INCHAR	;OUTPUT A CHARACTER TO THE SCREEN
MOV	AH,2
INT	21H
MOV	DX,OFFSET NEWLINE
MOV	AH,9		;MOVE CURSOR TO NEXT LINE
INT	21H
.EXIT
	MAIN ENDP
	CODE_SEG ENDS
	END MAIN
